- hosts: terraform-ansible
  tasks:
  - name: Instalando o Python3 e Virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes  
    become: yes
  - name: Instalando Dependencias com Pip (Django e Django Rest)
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name:
        - django
        - djangorestframework
  - name: Iniciando o Projeto
    shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
  - name: Alterando Hosts no Settings
    lineinfile:
      path: /home/ubuntu/tcc/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes