- hosts: django-venv
  tasks:
  - name: Instalando o Python3 e Virtualenv
    apt:
      name: "{{ item }}"
      state: latest
    become: yes
    with_items:
      - python3
      - python3-pip
      - virtualenv
    become: yes

  - name: Instalando Dependencias com Pip (Django e Django Rest)
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name:
        - django
        - djangorestframework
    become: yes

  - name: Iniciando o Projeto
    shell: '. /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/'
    become: yes

  - name: Alterando Hosts no Settings
    lineinfile:
      path: /home/ubuntu/tcc/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
    become: yes